[package]
name = "gluon-game"
version = "0.1.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
license = ""
readme = "README.md"

[dependencies]
# Game stuff
ggez = "0.4"
ggez-goodies = "0.1"
itertools = "0.8"
specs = "0.14"
shred = "0.8"
specs-derive = "0.1"
warmy = "0.7"

# Utility stuff
log = "0.4"
fern = {version = "0.5", features = ["colored"] }
chrono = "0.4"
failure = "0.1"

gluon = { path = "../gluon" }
gluon_vm = { path = "../gluon/vm" }
gluon_codegen = { path = "../gluon/codegen" }

[patch.crates-io]
shred = { path = "../shred" }
specs = { path = "../specs" }
